### Site info:
title: id研
tagline: 製作日記と作品集
author: idt12312
email: idossr12312[α]gmail.com
description: "id研 blog" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "id-ken, electronics, robot"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://idken.net" # the base hostname & protocol for your site
locale: en_US
permalink: /posts/:year-:month-:day-:title/

### Personal info and site tools info:
twitter_username: idt12312
github_username:  idt12312
disqus_shortname: idkenblog
favicon:     "/images/id_icon.png"
aboutme: 電子工作・ロボット、なにかをつくることが好きです.  # these are shown on aboutme-sidebar.
aboutme_photo: "/images/id_icon.png" # your photo.
google_analytics_key: UA-76753401-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr) and Russian (ru) 

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Cat: "
      Taggedwith: "Tag: "
      PostDate: "Date: "
      Google_search: "Site Search"
      Home: "Home"
      Works: "Works"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"

### your Blogroll info, only name can shown on the page.
Blogroll:
    - name: 東工大ロボット技術研究会
      href: https://www.rogiken.org/
      title: ロボット技術研究会のwebページ


### Build settings
exclude: ['Gemfile', 'Gemfile.lock', 'vendor', 'docker-compose.yml', 'new_post']

markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 13
excerpt_separator: "\n\n"
