#!/bin/sh

FILE_NAME="`date '+%Y-%m-%d'`-${1}.md"

touch _posts/$FILE_NAME

echo \
"---
layout: post
title: $2
category: $3
tag:
    - $4
comments: true
thumb: /images/thumb_default.svg
---
" > _posts/$FILE_NAME

